version: '2.1'
services:
  spark-master:
    build: livy-server
    container_name: spark-master
    ports:
      - "8080:8080" # spark master
      - "7077:7077" #
      - "8998:8998" # livy server
      - "18080:18080" # spark history server
    tty: true
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /Users/jitendrasachdeva/TW-DU/transformations/target/scala-2.11:/tmp/jars/

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  postgres:
    container_name: "postgres"
    image: postgres:9.6
    volumes:
      - ${HOME}/postgres_mount/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  webserver:
    container_name: "webserver"
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - postgres
    environment:
      - EXECUTOR=Local
      - AIRFLOW__CORE__FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
      - FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
    command: "webserver"
    volumes:
      - ${PWD}/dags:/usr/local/airflow/dags
      - ${PWD}/plugins:/usr/local/airflow/plugins
      - ${HOME}/airflow_mount/logs:/usr/local/airflow/logs
    ports:
      - "8090:8080"
      - "5555:5555"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3